### ISSUE TITLE
Availability of parsed parameters in yada.protocols/Properties

### ISSUE THREAD

**Issue by stijnopheide** [juxt/yada#32]
We already discussed this on slack, but maybe I should add it here too.

When calculating the properties on request ```(properties [_ ctx])``` arity, it would be nice to have parameters parsed already. This would mean that the ```get-properties``` interceptor would be executed after the ```malformed?``` interceptor.

As far as I can see, 
```
method-allowed?
process-request-body
malformed?
```
do not need anything that is processed in ```get-properties```, at least not the properties on request version. But I might be wrong on that one.

On the other hand if we have the output of ```malformed?``` already in the ctx, ```get-properties``` would be much easier to implement, especially if you need to query e.g. a database / filesystem to answer ```:exists?```, ```:representations```, ```:last-modified```, ...

**Comment by malcolmsparks** [comment]
If malformed? doesn't require properties to function, then you're right. We want malformed? to be processed as soon as possible, because a bad request should be thrown out as soon as possible, and not involved a database lookup.

I've checked all my resources, and none emit :parameters in the request version (although some emit :parameters in the 'static' non-request version) While I wanted to keep rules about which property can and can't be emitted in either version to a minimum, your case for bringing malformed? forward in the interceptor chain is compelling and I accept your argument - thanks for being so clear.

Perhaps malformed? is also poorly named. Maybe parse-parameters would be better. Of course, if those parameters end up being bad, and uncoerceably so, we send a 400 (Client Error).  The name is historic, via Liberator, so it's not essential we keep it. What do you think?

**Comment by stijnopheide** [comment]
Yes I think that would be a good change. The name comes from the spec I guess.

10.4.1 400 Bad Request
```The request could not be understood by the server due to malformed syntax.```

**Comment by malcolmsparks** [comment]
Closed since recent commits
