### ISSUE TITLE
Produces doesn't result in charset in content type

### ISSUE THREAD

**Issue by mdaley** [juxt/yada#56]
Hello, I can't say I'm certain about this, but I'm wondering why, when I specify a charset in produces for a resource, the response doesn't include the charset in the content type of the response?  My example is this (probably not the best place for it, but it shows the problem):

I changed the hello-world example to have a new resource:

```clojure
...
(defn say-hello-json [ctx]
  {:say "hello" :p (get-in ctx [:parameters :query :p])})
....
(defn hello-json []
  (yada
   (resource
    {:methods
     {:get
      {:parameters {:query {:p String}}
       :produces [{:media-type "application/json"
                   :charset "utf-8"}]
       :response say-hello-json}}}))) 
...
(routes
   ...
   ["hello-json" (tag (hello-json) ::hello-json)]
   ...
)
```

and I created a new test in `helloworld_test.clj` like this:

```clojure
(deftest json-test
  (let [resource (hello/hello-json)
        response @(resource (request :get "/?p=bob"))
        headers (:headers response)]
    (is (= 200 (:status response)))
    (is (= (to-string (:body response)) "{\"say\":\"hello\",\"p\":\"bob\"}"))
    (is (= (get-in response [:headers "content-type"]) "application/json;charset=utf-8"))))
```

My thinking is that, as I specified the resource to have `:produces` with `:charset "utf-8`, the response should have a content-type of `application/json;charset-utf-8`.  However the response only has the content-type `application/json`.

And my question is: is this a bug?  Or not?

Also, another point, I wonder why the actual body has a trailing `\n`?

If you look at my branch https://github.com/mdaley/yada you'll be able to see my check-in.

If this is a problem, if you give me some pointers, I'd be more than willing to be involved in fixing it.

**Comment by malcolmsparks** [comment]
There's some debate as to whether application/* types should have a charset
parameter.

My interpretation of the standards are that application/json should not
have a charset parameter since none is registered with IANA and including
it in the response Content-Type would be a violation of the standards. (If
there's any disagreement between de-jure and de-facto practice, yada tends
to go with the former.)

However, this doesn't remove the need for specifying the charset explicitly
in the produces declaration, because negotiation is still performed. JSON
allows 3 possible charsets: utf-8, utf-16 and utf-32. A byte-order mark is
used to distinguish between these cases. In a future version, yada may
convert your output to the negotiated charset (I can't remember right now
if it already does this).

**Comment by malcolmsparks** [comment]
Having said all that, I've noticed that Chrome and Firefox both refuse to render in UTF-8 unless the charset is explicitly set on the content-type.

See
http://stackoverflow.com/questions/19814908/why-content-type-header-to-use-for-json-application-json-charset-utf-8-or

particularly the comment:

> There is no charset parameter defined for application/json – Julian Reschke Nov 6 '13 at 15:16 

(Julian Reshke is one of the authors of https://tools.ietf.org/html/rfc7231)

So this looks like a bug in both Chrome and Firefox. But I'm not sure how much influence I have on those teams :(

**Comment by mdaley** [comment]
Sorry, apologies for tardiness, I'm sure I replied to you a few days' ago saying that, having read around a bit, I agreed with what you said.  Perhaps I didn't present the submit button or something else failed?

Anyway that's interesting - the thing about Chrome and Firefox.  As is the comment in the stackoverflow question you linked.  Before (where I work) we used clojure we used Spring; perhaps we got the charset=utf-8 addition from there and have just perpetuated it.

Personally, I would be happy if you closed this Issue as I was wrong in the first place.  But I'm glad that I've highlighted the Chrome/Firefox issue.
