### ISSUE TITLE
yada doesn't accept "application/transit+json; charset=utf-8"

### ISSUE THREAD

**Issue by Frozenlock** [juxt/yada#88]
[cljs-ajax](https://github.com/JulianBirch/cljs-ajax) automatically adds `; charset=utf-8` to the accept header when using the transit format.

This causes Yada to return a 406 (not acceptable).

A quick read of #56 left me with the impression that Yada is still supposed to return application/transit+json and drop the charset argument.

Is this a bug? Perhaps there's some configuration one needs to add to be able to accept the `application/transit+json; charset=utf-8`?

**Comment by malcolmsparks** [comment]
It's a bug in cljs-ajax, in my opinion, since the charset parameter is not
a registered parameter of application/json at IANA. The JSON spec.
specifies utf8, utf16 and utf32, the latter being determined by a
byte-order mark.

The habit of adding the charset parameter has come across from text/* where
it is indeed a registered parameter. I'm reluctant to 'fix' yada to support
this  because it perpetuates this bad practice.

Incidentally, what's your :consumes declaration?

Shall I raise an issue with cljs-ajax?
On 13 Apr 2016 04:08, "Frozenlock" <notifications@github.com> wrote:

cljs-ajax <https://github.com/JulianBirch/cljs-ajax> automatically adds ;
charset=utf-8 to the accept header when using the transit format.

This causes Yada to return a 406 (not acceptable).

A quick read of #56 <https://github.com/juxt/yada/issues/56> left me with
the impression that Yada is still supposed to return
application/transit+json and drop the charset argument.

Is this a bug? Perhaps there's some configuration one needs to add to be
able to accept the application/transit+json; charset=utf-8?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/juxt/yada/issues/88>

**Comment by Frozenlock** [comment]
@malcolmsparks thanks for to quick answer.

`:consumes` declaration:

```clj
(def produced-types
  #{"application/transit+json"
    ;"application/transit+msgpack"
    "application/json" 
    "application/edn" 
    "text/html"})


(def consumed-types
  #{"application/transit+json"
    ;"application/transit+msgpack"
    "application/json" 
    "application/edn"})
```

``` clj
{:produces [{:media-type produced-types
                :charset "UTF-8"}]
 :consumes [{:media-type consumed-types
                :charset "UTF-8"}]
...}
```

Regarding opening an issue with `cljs-ajax`, you might be in a better position to explain your view.
If you don't open one, I'll probably do it tomorrow using what you said here.

**Comment by malcolmsparks** [comment]
Julian says he's aware of the issue.

**Comment by Frozenlock** [comment]
I'll close this as there is nothing to do in Yada.
